# Welcome!

# 1. 기초 라이브러리 명령어 학습

## 1.2 pandas 라이브러리

Pandas는 열과 행으로 이루어져 있는 Table을 처리하고 가공하는 라이브러리로, Python으로 데이터를 다룰 때 빠질 수 없는 아주 중요한 패키지입니다. 한 열로 구성된 1차원 형태의 Series, 열들이 모여 Table을 이루는 DataFrame, 2가지 자료형으로 구성되어 있습니다.

<img src="https://dandyrilla.github.io/images/2017-08-12/fig0.png" width="400" height="400" />

In [41]:
import numpy as np
import pandas as pd

### Series와 DataFrame 기초

#### Series

In [42]:
# Series는 1차원 배열로 실제 값들이 나열되어 있는 Value와 이러한 값들에 번호를 매기는 Index로 구성되어 있습니다.
# index가 따로 지정되지 않으면, 자동으로 0부터 순차적으로 지정됩니다
a = [1,2,3,4,5]
a_series = pd.Series(a)
print(a)
print(a_series)

[1, 2, 3, 4, 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64

## DataFrame

In [43]:
# DataFrame은 2치원 형태의 자료구조이며, 행은 Index 번호로, 열은 column 이름으로 구분합니다.
raw_data = {'col0': [1,2,3,4,5],
           'col1': [10,20,30,40,50],
           'col2': [100,200,300,400,500]}
df = pd.DataFrame(raw_data)
df

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400
4     5    50   500

In [44]:
# DataFrame의 각 열은 Series가 됩니다.
df['col0']

0    1
1    2
2    3
3    4
4    5
Name: col0, dtype: int64

In [45]:
df.col0

0    1
1    2
2    3
3    4
4    5
Name: col0, dtype: int64

In [46]:
# Dataframe에 열을 추가할 수 있습니다.
new=['딸기', '당근', '수박', '참외', '메론']
df['new column'] = new
df

   col0  col1  col2 new column
0     1    10   100         딸기
1     2    20   200         당근
2     3    30   300         수박
3     4    40   400         참외
4     5    50   500         메론

In [47]:
# del 명렁어로 열을 삭제할 수도 있습니다
del df['col2']
df

   col0  col1 new column
0     1    10         딸기
1     2    20         당근
2     3    30         수박
3     4    40         참외
4     5    50         메론

In [48]:
# drop 명렁어로 열을 제외할때는 axis=1 명시
df.drop('new column', axis=1)

   col0  col1
0     1    10
1     2    20
2     3    30
3     4    40
4     5    50

### loc & iloc

In [49]:
# loc 명령어를 통해 DataFrame의 특정 행, 특정 열을 추출할 수 있습니다
# loc은 index와 column 값 기준
df.loc[3]     #특정 행만 추출

col0           4
col1          40
new column    참외
Name: 3, dtype: object

In [50]:
df.loc[1,['col0']]

col0    2
Name: 1, dtype: int64

In [51]:
df.loc[1:4,:] #특정 행과 모든 열

   col0  col1 new column
1     2    20         당근
2     3    30         수박
3     4    40         참외
4     5    50         메론

In [52]:
df.loc[:,['col0','new column']] #특정 열과 모든 행

   col0 new column
0     1         딸기
1     2         당근
2     3         수박
3     4         참외
4     5         메론

In [53]:
df.loc[3:5,['col1','new column']]  #특정 열과 특정 행

   col1 new column
3    40         참외
4    50         메론

In [54]:
df.loc[[1,2,4],['col1','new column']] #특정 열과 특정 행

   col1 new column
1    20         당근
2    30         수박
4    50         메론

In [55]:
# 컬럼 순서 변경
df.loc[:,['new column', 'col1', 'col0']]

  new column  col1  col0
0         딸기    10     1
1         당근    20     2
2         수박    30     3
3         참외    40     4
4         메론    50     5

In [56]:
#iloc은 실제 배열 순서 기준으로 통해 DataFrame의 특정 행, 특정 열을 추출할 수 있습니다

In [57]:
df.iloc[[1,3],[2]]      #iloc은 실제 배열 순서 기준

  new column
1         당근
3         참외

In [58]:
# DataFrame도 전치(행과 열을 바꿈)할 수 있습니다
df.T

             0   1   2   3   4
col0         1   2   3   4   5
col1        10  20  30  40  50
new column  딸기  당근  수박  참외  메론

In [59]:
df

   col0  col1 new column
0     1    10         딸기
1     2    20         당근
2     3    30         수박
3     4    40         참외
4     5    50         메론

In [60]:
(df['col1'] <= 30) & (df['new column'] == '딸기')

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [61]:
# col1 30도 이하이고, new column 딸기이면, 산다는 데이터를 입력해봅시다.
df['buy'] = (df['col1'] <= 30) & (df['new column'] == '딸기')
df

   col0  col1 new column    buy
0     1    10         딸기   True
1     2    20         당근  False
2     3    30         수박  False
3     4    40         참외  False
4     5    50         메론  False

## Import data

In [62]:
# pd.set_option('display.max_columns', None)

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_rows', 60)

In [63]:
# csv 불러오기
flight_data = pd.read_csv('data/nycflights13.csv')


flight_data

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,JFK,DCA,NaN,213,14,55
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,LGA,SYR,NaN,198,22,0
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,LGA,BNA,NaN,764,12,10
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,LGA,CLE,NaN,419,11,59
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,LGA,RDU,NaN,431,8,40

## Select columns
Select the `origin`, `dest`, and `hour` columns

In [64]:
flight_data.loc[:, ['origin', 'dest', 'hour']]

       origin dest  hour
0         EWR  IAH     5
1         LGA  IAH     5
2         JFK  MIA     5
3         JFK  BQN     5
4         LGA  ATL     6
...       ...  ...   ...
336771    JFK  DCA    14
336772    LGA  SYR    22
336773    LGA  BNA    12
336774    LGA  CLE    11
336775    LGA  RDU     8

[336776 rows x 3 columns]

In [65]:
# Pandorigin이 LGA 인 경우, 'origin', 'dest', 'hour' 호출
flight_data.loc[flight_data['origin']=='LGA', ['origin', 'dest', 'hour']]

       origin dest  hour
1         LGA  IAH     5
4         LGA  ATL     6
7         LGA  IAD     6
9         LGA  ORD     6
14        LGA  DFW     6
...       ...  ...   ...
336770    LGA  BNA    18
336772    LGA  SYR    22
336773    LGA  BNA    12
336774    LGA  CLE    11
336775    LGA  RDU     8

[104662 rows x 3 columns]

In [66]:
# 새로운 데이터프레임 생성
new_df = flight_data.loc[flight_data['origin']=='LGA', ['origin', 'dest', 'hour']]

new_df

       origin dest  hour
1         LGA  IAH     5
4         LGA  ATL     6
7         LGA  IAD     6
9         LGA  ORD     6
14        LGA  DFW     6
...       ...  ...   ...
336770    LGA  BNA    18
336772    LGA  SYR    22
336773    LGA  BNA    12
336774    LGA  CLE    11
336775    LGA  RDU     8

[104662 rows x 3 columns]

## Drop columns

In [67]:
flight_subset = new_df.drop(['hour'], axis=1).head()
flight_subset

   origin dest
1     LGA  IAH
4     LGA  ATL
7     LGA  IAD
9     LGA  ORD
14    LGA  DFW

## Filter rows
Select all flights longer than 10 hours that flew from JFK airport on January 1

In [68]:
# AND
flight_data[(flight_data['month'] == 1) &
            (flight_data['day'] == 1) &
            (flight_data['origin'] == 'JFK') &
            (flight_data['hour'] > 10)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,JFK,BWI,41.0,184,18,35
258,2013,1,1,1059.0,1100,-1.0,1210.0,1215,-5.0,MQ,JFK,DCA,50.0,213,11,0
265,2013,1,1,1111.0,1115,-4.0,1222.0,1226,-4.0,B6,JFK,BTV,52.0,266,11,15
266,2013,1,1,1112.0,1100,12.0,1440.0,1438,2.0,UA,JFK,SFO,364.0,2586,11,0
272,2013,1,1,1124.0,1100,24.0,1435.0,1431,4.0,B6,JFK,SFO,349.0,2586,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,2013,1,1,2326.0,2130,116.0,131.0,18,73.0,B6,JFK,LAS,290.0,2248,21,30
833,2013,1,1,2327.0,2250,37.0,32.0,2359,33.0,B6,JFK,SYR,45.0,209,22,50
835,2013,1,1,2353.0,2359,-6.0,425.0,445,-20.0,B6,JFK,PSE,195.0,1617,23,59
836,2013,1,1,2353.0,2359,-6.0,418.0,442,-24.0,B6,JFK,SJU,185.0,1598,23,59
837,2013,1,1,2356.0,2359,-3.0,425.0,437,-12.0,B6,JFK,BQN,186.0,1576,23,59

In [69]:
# OR
flight_data[(flight_data['month'] == 1) |
            (flight_data['origin'] == 'JFK') |
            (flight_data['origin'] == 'LGA')]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,JFK,DCA,NaN,213,14,55
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,LGA,SYR,NaN,198,22,0
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,LGA,BNA,NaN,764,12,10
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,LGA,CLE,NaN,419,11,59
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,LGA,RDU,NaN,431,8,40

## Working with Nan

In [70]:
flight_data_nan = flight_data
flight_data_nan.dtypes

year                int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier               str
origin                str
dest                  str
air_time          float64
distance            int64
hour                int64
minute              int64
dtype: object

In [71]:
# Check observation count
flight_data_nan.count()

year              336776
month             336776
day               336776
dep_time          328521
sched_dep_time    336776
dep_delay         328521
arr_time          328063
sched_arr_time    336776
arr_delay         327346
carrier           336776
origin            336776
dest              336776
air_time          327346
distance          336776
hour              336776
minute            336776
dtype: int64

In [72]:
flight_data_nan['arr_delay'].isna()

0         False
1         False
2         False
3         False
4         False
          ...
336771     True
336772     True
336773     True
336774     True
336775     True
Name: arr_delay, Length: 336776, dtype: bool

In [73]:
# 결측치 있는 행만 골라내기
flight_data_nan.loc[flight_data_nan['arr_delay'].isna(), :]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
471,2013,1,1,1525.0,1530,-5.0,1934.0,1805,NaN,MQ,LGA,XNA,NaN,1147,15,30
477,2013,1,1,1528.0,1459,29.0,2002.0,1647,NaN,EV,EWR,STL,NaN,872,14,59
615,2013,1,1,1740.0,1745,-5.0,2158.0,2020,NaN,MQ,LGA,XNA,NaN,1147,17,45
643,2013,1,1,1807.0,1738,29.0,2251.0,2103,NaN,UA,EWR,SAN,NaN,2425,17,38
725,2013,1,1,1939.0,1840,59.0,29.0,2151,NaN,9E,JFK,DFW,NaN,1391,18,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,JFK,DCA,NaN,213,14,55
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,LGA,SYR,NaN,198,22,0
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,LGA,BNA,NaN,764,12,10
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,LGA,CLE,NaN,419,11,59
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,LGA,RDU,NaN,431,8,40

In [74]:
# 결측치 없는 행만 골라내기
flight_data_nan.loc[flight_data_nan['arr_delay'].notna(), :]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336765,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,JFK,SYR,41.0,209,22,45
336766,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,JFK,BUF,52.0,301,22,50
336767,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,JFK,ROC,47.0,264,22,46
336768,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,JFK,BOS,33.0,187,22,55
336769,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,JFK,PSE,196.0,1617,23,59

In [75]:
# Filling missing
flight_data_nan['arr_delay'] = flight_data_nan['arr_delay'].fillna(0)

In [76]:
flight_data_nan.count()

year              336776
month             336776
day               336776
dep_time          328521
sched_dep_time    336776
dep_delay         328521
arr_time          328063
sched_arr_time    336776
arr_delay         336776
carrier           336776
origin            336776
dest              336776
air_time          327346
distance          336776
hour              336776
minute            336776
dtype: int64

In [77]:
flight_data_nan.count()

year              336776
month             336776
day               336776
dep_time          328521
sched_dep_time    336776
dep_delay         328521
arr_time          328063
sched_arr_time    336776
arr_delay         336776
carrier           336776
origin            336776
dest              336776
air_time          327346
distance          336776
hour              336776
minute            336776
dtype: int64

In [78]:
flight_data

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,0.0,9E,JFK,DCA,NaN,213,14,55
336772,2013,9,30,NaN,2200,NaN,NaN,2312,0.0,9E,LGA,SYR,NaN,198,22,0
336773,2013,9,30,NaN,1210,NaN,NaN,1330,0.0,MQ,LGA,BNA,NaN,764,12,10
336774,2013,9,30,NaN,1159,NaN,NaN,1344,0.0,MQ,LGA,CLE,NaN,419,11,59
336775,2013,9,30,NaN,840,NaN,NaN,1020,0.0,MQ,LGA,RDU,NaN,431,8,40

## Sort rows

In [79]:
# Pandas
flight_data.sort_values(by=['distance', 'hour'], ascending=True).head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute
275945,2013,7,27,NaN,106,NaN,NaN,245,0.0,US,EWR,LGA,NaN,17,1,6
3083,2013,1,4,1240.0,1200,40.0,1333.0,1306,27.0,EV,EWR,PHL,30.0,80,12,0
3901,2013,1,5,1155.0,1200,-5.0,1241.0,1306,-25.0,EV,EWR,PHL,29.0,80,12,0
3426,2013,1,4,1829.0,1615,134.0,1937.0,1721,136.0,EV,EWR,PHL,28.0,80,16,15
10235,2013,1,12,1613.0,1617,-4.0,1708.0,1722,-14.0,EV,EWR,PHL,36.0,80,16,17

## Add new columns

In [80]:
# Pandas
df = flight_data
df['new_distance'] = df['distance'] / 1000
df['carrier_origin'] = df['carrier'] + df['origin']

df

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute,new_distance,carrier_origin
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15,1.400,UAEWR
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29,1.416,UALGA
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40,1.089,AAJFK
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45,1.576,B6JFK
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0,0.762,DLLGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,0.0,9E,JFK,DCA,NaN,213,14,55,0.213,9EJFK
336772,2013,9,30,NaN,2200,NaN,NaN,2312,0.0,9E,LGA,SYR,NaN,198,22,0,0.198,9ELGA
336773,2013,9,30,NaN,1210,NaN,NaN,1330,0.0,MQ,LGA,BNA,NaN,764,12,10,0.764,MQLGA
336774,2013,9,30,NaN,1159,NaN,NaN,1344,0.0,MQ,LGA,CLE,NaN,419,11,59,0.419,MQLGA
336775,2013,9,30,NaN,840,NaN,NaN,1020,0.0,MQ,LGA,RDU,NaN,431,8,40,0.431,MQLGA

## Group data

In [81]:
flight_data.groupby('origin')['distance'].agg(['mean'])

               mean
origin
EWR     1056.742790
JFK     1266.249077
LGA      779.835671

In [82]:
# Reset_index
flight_data.groupby('origin')['distance'].agg(['mean']).reset_index()

  origin         mean
0    EWR  1056.742790
1    JFK  1266.249077
2    LGA   779.835671

In [83]:
# rename columns
flight_data.groupby('origin')['distance'].agg(mean_dist='mean').reset_index()

  origin    mean_dist
0    EWR  1056.742790
1    JFK  1266.249077
2    LGA   779.835671

## Group and Multiple Summarize

In [84]:
flight_data.groupby(['origin'])[['distance']].agg(['mean', 'first'])

           distance
               mean first
origin
EWR     1056.742790  1400
JFK     1266.249077  1089
LGA      779.835671  1416

In [85]:
# Drop index level
flight_data.groupby('origin')['distance'].agg(
    dist_mean='mean',
    dist_first='first'
).reset_index()

  origin    dist_mean  dist_first
0    EWR  1056.742790        1400
1    JFK  1266.249077        1089
2    LGA   779.835671        1416

## Group Two-level data

In [86]:
flight_data.groupby(['origin', 'dest'])['distance'].agg(
    mean_distance='mean',
    sum_distance='sum'
).reset_index()

    origin dest  mean_distance  sum_distance
0      EWR  ALB          143.0         62777
1      EWR  ANC         3370.0         26960
2      EWR  ATL          746.0       3746412
3      EWR  AUS         1504.0       1455872
4      EWR  AVL          583.0        154495
..     ...  ...            ...           ...
219    LGA  SYR          198.0         58014
220    LGA  TPA         1010.0       2166450
221    LGA  TVC          655.0         50435
222    LGA  TYS          647.0        199276
223    LGA  XNA         1147.0        854515

[224 rows x 4 columns]

## Group Two-level data & multiple summarize

In [87]:
new_df = flight_data.groupby(['origin', 'dest']).agg(
    dist_mean=('distance', 'mean'),
    dist_sum=('distance', 'sum'),
    delay_mean=('arr_delay', 'mean')
).reset_index()
new_df

    origin dest  dist_mean  dist_sum  delay_mean
0      EWR  ALB      143.0     62777   13.708428
1      EWR  ANC     3370.0     26960   -2.500000
2      EWR  ATL      746.0   3746412   12.848467
3      EWR  AUS     1504.0   1455872   -0.469008
4      EWR  AVL      583.0    154495    8.339623
..     ...  ...        ...       ...         ...
219    LGA  SYR      198.0     58014    8.494881
220    LGA  TPA     1010.0   2166450    8.133800
221    LGA  TVC      655.0     50435   15.142857
222    LGA  TYS      647.0    199276    3.350649
223    LGA  XNA     1147.0    854515    6.770470

[224 rows x 5 columns]

## Mutating Categorical Data : Map and Cut

In [88]:
flight_data

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute,new_distance,carrier_origin
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15,1.400,UAEWR
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29,1.416,UALGA
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40,1.089,AAJFK
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45,1.576,B6JFK
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0,0.762,DLLGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,0.0,9E,JFK,DCA,NaN,213,14,55,0.213,9EJFK
336772,2013,9,30,NaN,2200,NaN,NaN,2312,0.0,9E,LGA,SYR,NaN,198,22,0,0.198,9ELGA
336773,2013,9,30,NaN,1210,NaN,NaN,1330,0.0,MQ,LGA,BNA,NaN,764,12,10,0.764,MQLGA
336774,2013,9,30,NaN,1159,NaN,NaN,1344,0.0,MQ,LGA,CLE,NaN,419,11,59,0.419,MQLGA
336775,2013,9,30,NaN,840,NaN,NaN,1020,0.0,MQ,LGA,RDU,NaN,431,8,40,0.431,MQLGA

In [89]:
flight_data.carrier.unique()

<StringArray>
['UA', 'AA', 'B6', 'DL', 'EV', 'MQ', 'US', 'WN', 'VX', 'FL', 'AS', '9E', 'F9',
 'HA', 'YV', 'OO']
Length: 16, dtype: str

In [90]:
# 1. 항공사 그룹 리스트 정의 (가독성 향상)
class_A = ['UA', 'AA', 'B6', 'DL', 'EV', 'MQ', 'US']
class_B = ['WN', 'VX', 'FL', 'AS', '9E', 'F9', 'HA', 'YV', 'OO']

# 2. 조건 및 결과 지정
conditions = [
    flight_data['carrier'].isin(class_A),
    flight_data['carrier'].isin(class_B)
]
choices = ['A', 'B']

# 3. 매핑 실행 (리스트에 없는 신규 항공사는 'Other'로 지정)
flight_data['carrier_class'] = np.select(conditions, choices, default='Other')
flight_data[['carrier', 'carrier_class']].sample(n=10)

       carrier carrier_class
271519      MQ             A
320172      UA             A
153796      B6             A
98054       DL             A
203477      UA             A
45029       B6             A
185948      EV             A
32788       B6             A
160445      UA             A
198322      B6             A

In [91]:
flight_data[['carrier', 'carrier_class']].sample(n=10)

       carrier carrier_class
232720      EV             A
302828      DL             A
112459      EV             A
292985      B6             A
193776      UA             A
21737       UA             A
188829      EV             A
89009       EV             A
139046      MQ             A
71554       B6             A

In [92]:
# flight_data['cacarrier_class']=='UA'이면,  'carricarrier_class' 를 'B'로 변환해서 수정

flight_data.loc[flight_data['carrier']=='UA', 'carrier_class'] = 'B'


flight_data[['carrier', 'carrier_class']].sample(n=10)

       carrier carrier_class
35250       AA             A
72772       9E             B
230097      EV             A
126230      9E             B
300868      MQ             A
5786        DL             A
170999      UA             B
234765      EV             A
206985      EV             A
195840      B6             A

In [93]:
flight_data.distance.describe()

count    336776.000000
mean       1039.912604
std         733.233033
min          17.000000
25%         502.000000
50%         872.000000
75%        1389.000000
max        4983.000000
Name: distance, dtype: float64

In [94]:
# Caterorical variable from Continuous Variable

# 0 포함(include_lowest=True) 및 5000 초과 거리 무한대(np.inf) 커버
bins = [0, 502, 872, 1389, np.inf]
labels = ["very_short", "short", "long", "very_long"]
flight_data['distance_class'] = pd.cut(
    flight_data['distance'], 
    bins=bins, 
    labels=labels,
    include_lowest=True  # 0 값도 안전하게 구간에 포함
)
flight_data[['distance', 'distance_class']].sample(n=10)

        distance distance_class
224675      2565      very_long
276102       416     very_short
131905        94     very_short
129750      1215           long
287617      1605      very_long
308283      2576      very_long
249912       529          short
103904      2425      very_long
28983       1008           long
93530        214     very_short

## 연습문제 02

* \[Step 1\]: Filter out all flights longer than 10 hours
* \[Step 2\]: Create a new column, `speed`, using the formula [distance / (air time * 60)]
* \[Step 3\]: Calculate the mean speed for flights originating from each airport
* \[Step 4\]: Sort the result by mean speed in descending order

In [95]:
# 1. hour가 10 초과인 데이터 필터링 (.copy()로 경고 방지)
filtered_data = flight_data[flight_data['hour'] > 10].copy()
# 2. 속도(mph) 계산 및 컬럼 추가
filtered_data['speed'] = (filtered_data['distance'] / filtered_data['air_time']) * 60
# 3. origin별 평균 속도 계산 및 정렬
result = (
    filtered_data.groupby('origin')['speed']
    .agg(mean_speed='mean')
    .reset_index()
    .sort_values('mean_speed', ascending=False)
)
result

  origin  mean_speed
0    EWR  395.196642
1    JFK  393.936754
2    LGA  386.504906

## From Wide to Long

In [96]:
# 1. 가로로 넓은 형태의 예시 데이터프레임 생성
data = {
    'id': [1, 2],
    'A2020': [100, 200],
    'A2021': [120, 220],
    'B2020': [15, 25],
    'B2021': [18, 28]
}
df = pd.DataFrame(data)
df

   id  A2020  A2021  B2020  B2021
0   1    100    120     15     18
1   2    200    220     25     28

In [97]:
# 2. pd.wide_to_long으로 변환
# - stubnames=["A", "B"]: 변환할 컬럼명의 공통 접두사
# - i="id": 각 행을 구분하는 식별자
# - j="year": 접두사 뒤에 붙은 숫자가 새로 들어갈 컬럼명
df_long = pd.wide_to_long(df, stubnames=["A", "B"], i="id", j="year").reset_index()

df_long

   id  year    A   B
0   1  2020  100  15
1   2  2020  200  25
2   1  2021  120  18
3   2  2021  220  28

In [98]:
# 1. 다중 식별자를 가진 Wide 형태 데이터프레임 생성
# famid(가족ID), birth(출생순위), ht1(1세 때 키), ht2(2세 때 키)
df = pd.DataFrame({
    'famid': [1, 1, 2, 2],
    'birth': [1, 2, 1, 2],
    'ht1': [50, 48, 52, 51],
    'ht2': [80, 76, 82, 81]
})
df

   famid  birth  ht1  ht2
0      1      1   50   80
1      1      2   48   76
2      2      1   52   82
3      2      2   51   81

In [99]:
# 2. pd.wide_to_long 실행
# - stubnames='ht': 변환할 컬럼명의 공통 접두사 ('ht')
# - i=['famid', 'birth']: 다중 식별자 컬럼 리스트
# - j='age': ht1, ht2의 숫자(1, 2)가 새로 들어갈 컬럼명
result = pd.wide_to_long(df, stubnames='ht', i=['famid', 'birth'], j='age').reset_index()
result

   famid  birth  age  ht
0      1      1    1  50
1      1      1    2  80
2      1      2    1  48
3      1      2    2  76
4      2      1    1  52
5      2      1    2  82
6      2      2    1  51
7      2      2    2  81

In [100]:
df = pd.DataFrame({
    'date' : ['05/03', '06/03', '07/03', '08/03'],
    'AA' : [1, 4, 7, 5],
    'BB' : [2, 5, 8, 7],
    'CC' : [3, 6, 9, 1]
}).set_index('date')

df = df.reset_index()
df

    date  AA  BB  CC
0  05/03   1   2   3
1  06/03   4   5   6
2  07/03   7   8   9
3  08/03   5   7   1

In [101]:
# Use pd.melt

pd.melt(df, id_vars='date', value_vars=['AA', 'BB', 'CC'])

     date variable  value
0   05/03       AA      1
1   06/03       AA      4
2   07/03       AA      7
3   08/03       AA      5
4   05/03       BB      2
5   06/03       BB      5
6   07/03       BB      8
7   08/03       BB      7
8   05/03       CC      3
9   06/03       CC      6
10  07/03       CC      9
11  08/03       CC      1

## Join

In [102]:
# 복사본 생성
flight_data_reset  = flight_data

flight_data_reset

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,origin,dest,air_time,distance,hour,minute,new_distance,carrier_origin,carrier_class,distance_class
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,EWR,IAH,227.0,1400,5,15,1.400,UAEWR,B,very_long
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,LGA,IAH,227.0,1416,5,29,1.416,UALGA,B,very_long
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,JFK,MIA,160.0,1089,5,40,1.089,AAJFK,A,long
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,JFK,BQN,183.0,1576,5,45,1.576,B6JFK,A,very_long
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,LGA,ATL,116.0,762,6,0,0.762,DLLGA,A,short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,0.0,9E,JFK,DCA,NaN,213,14,55,0.213,9EJFK,B,very_short
336772,2013,9,30,NaN,2200,NaN,NaN,2312,0.0,9E,LGA,SYR,NaN,198,22,0,0.198,9ELGA,B,very_short
336773,2013,9,30,NaN,1210,NaN,NaN,1330,0.0,MQ,LGA,BNA,NaN,764,12,10,0.764,MQLGA,A,short
336774,2013,9,30,NaN,1159,NaN,NaN,1344,0.0,MQ,LGA,CLE,NaN,419,11,59,0.419,MQLGA,A,very_short
336775,2013,9,30,NaN,840,NaN,NaN,1020,0.0,MQ,LGA,RDU,NaN,431,8,40,0.431,MQLGA,A,very_short

In [103]:

# index를 활용해서 id 컬럼 생성

flight_data_reset['id'] = range(1, len(flight_data_reset) + 1)

flight_data_reset

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,dest,air_time,distance,hour,minute,new_distance,carrier_origin,carrier_class,distance_class,id
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,IAH,227.0,1400,5,15,1.400,UAEWR,B,very_long,1
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,IAH,227.0,1416,5,29,1.416,UALGA,B,very_long,2
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,MIA,160.0,1089,5,40,1.089,AAJFK,A,long,3
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,BQN,183.0,1576,5,45,1.576,B6JFK,A,very_long,4
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,ATL,116.0,762,6,0,0.762,DLLGA,A,short,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,0.0,9E,...,DCA,NaN,213,14,55,0.213,9EJFK,B,very_short,336772
336772,2013,9,30,NaN,2200,NaN,NaN,2312,0.0,9E,...,SYR,NaN,198,22,0,0.198,9ELGA,B,very_short,336773
336773,2013,9,30,NaN,1210,NaN,NaN,1330,0.0,MQ,...,BNA,NaN,764,12,10,0.764,MQLGA,A,short,336774
336774,2013,9,30,NaN,1159,NaN,NaN,1344,0.0,MQ,...,CLE,NaN,419,11,59,0.419,MQLGA,A,very_short,336775
336775,2013,9,30,NaN,840,NaN,NaN,1020,0.0,MQ,...,RDU,NaN,431,8,40,0.431,MQLGA,A,very_short,336776

In [104]:
# id 컬럼을 공유하는 두 개의 데이터 프레임 생성
flight_distance = flight_data_reset.loc[flight_data_reset['carrier'].isin(['DL','AA']), ['id','carrier','distance']] # DL, AA
flight_time = flight_data_reset.loc[flight_data_reset['carrier'].isin(['AA']), ['id','carrier','air_time']] #  AA 만

In [105]:
flight_distance

            id carrier  distance
2            3      AA      1089
4            5      DL       762
9           10      AA       733
14          15      AA      1389
20          21      DL      1020
...        ...     ...       ...
336709  336710      AA       733
336715  336716      DL       187
336718  336719      DL      1598
336744  336745      DL      2475
336751  336752      AA      2475

[80839 rows x 3 columns]

In [106]:
flight_time

            id carrier  air_time
2            3      AA     160.0
9           10      AA     138.0
14          15      AA     257.0
22          23      AA     152.0
31          32      AA     153.0
...        ...     ...       ...
336653  336654      AA     150.0
336700  336701      AA      37.0
336704  336705      AA     294.0
336709  336710      AA     105.0
336751  336752      AA     298.0

[32729 rows x 3 columns]

병합 방식은 크게 inner, outer, left, right 방식이 있습니다.
* inner join 방식 : 좌측 table과 우측 table의 기준열에서 key 값이 모두 존재하는 경우에만 병합
* outer join 방식 : 좌측 table과 우측 table의 기준열에서 key 값이 모두 존재하지 않아도 병합
* left join 방식 : 좌측 table의 기준열만 고려하여 병합
* right join 방식 : 우측 table의 기준열만 고려하여 병합

여기서는 많이 사용하는 inner join, left join에 대해서만 배우겠습니다.

<img src="https://static.wixstatic.com/media/2f98e9_c5999377496a4e399bbc042ffe3280fc~mv2.jpg" width="600" height="400" />

In [107]:
# 왼쪽의 기준 Table을 먼저 쓰고, 오른쪽의 병합 Table을 다음에 씁니다. left_on과 right_on은 각각 Table의 기준열입니다.
#inner join 방식입니다. inner join이  default 설정이기 때문에 how = 'inner' parameter를 넣지 않아도 됩니다.

flight_inner = pd.merge(flight_distance, flight_time, left_on='id', right_on="id", how='inner')

flight_inner

           id carrier_x  distance carrier_y  air_time
0           3        AA      1089        AA     160.0
1          10        AA       733        AA     138.0
2          15        AA      1389        AA     257.0
3          23        AA      1085        AA     152.0
4          32        AA      1096        AA     153.0
...       ...       ...       ...       ...       ...
32724  336654        AA      1096        AA     150.0
32725  336701        AA       187        AA      37.0
32726  336705        AA      2475        AA     294.0
32727  336710        AA       733        AA     105.0
32728  336752        AA      2475        AA     298.0

[32729 rows x 5 columns]

flight_distance은 80839개의 행을 가지고 있었으나, inner join은 'flight_distance' 'flight_time'에 공통적으로 포함된 값들만 살리고, 이들을 기준으로 데이터를 병합합니다. 따라서 flight_distance에서 carrier가 AA가 아닌 행들은 모두 삭제됩니다.

In [108]:
#left join 방식입니다.
flight_left = pd.merge(flight_distance, flight_time, left_on='id', right_on="id", how='left')

flight_left

           id carrier_x  distance carrier_y  air_time
0           3        AA      1089        AA     160.0
1           5        DL       762       NaN       NaN
2          10        AA       733        AA     138.0
3          15        AA      1389        AA     257.0
4          21        DL      1020       NaN       NaN
...       ...       ...       ...       ...       ...
80834  336710        AA       733        AA     105.0
80835  336716        DL       187       NaN       NaN
80836  336719        DL      1598       NaN       NaN
80837  336745        DL      2475       NaN       NaN
80838  336752        AA      2475        AA     298.0

[80839 rows x 5 columns]

left join은 왼쪽의 기준테이블의 모든행을 유지합니다. 따라서 flight_distance은 80839개의 행을 모두 유지합니다. 기준테이블과 결합테이블 간에 일치하지 않는 행은 결측치가 입력됩니다.

## Stacking

In [109]:
# @title 기본 제목 텍스트
df1 = pd.DataFrame([['A0', 'A1', 'A2', 'A3'],
                    ['B0', 'B1', 'B2', 'B3'],
                    ['C0', 'C1', 'C2', 'C3'],
                    ['D0', 'D1', 'D2', 'D3']], columns=list('ABCD'))

df2 = pd.DataFrame([['A4', 'A5', 'A6', 'A7'],
                    ['B4', 'B5', 'B6', 'B7'],
                    ['C4', 'C5', 'C6', 'C7'],
                    ['D4', 'D5', 'D6', 'D7']], columns=['A', 'B', 'C', 'D'], index=[2, 3, 4, 5])

df3 = pd.DataFrame([['A8', 'A9', 'A10', 'A11'],
                    ['B8', 'B9', 'B10', 'B11'],
                    ['C8', 'C9', 'C10', 'C11'],
                    ['D8', 'D9', 'D10', 'D11']], columns=list('ABCD'), index=[5, 6, 7, 8])

In [110]:
df1

    A   B   C   D
0  A0  A1  A2  A3
1  B0  B1  B2  B3
2  C0  C1  C2  C3
3  D0  D1  D2  D3

In [111]:
df2

    A   B   C   D
2  A4  A5  A6  A7
3  B4  B5  B6  B7
4  C4  C5  C6  C7
5  D4  D5  D6  D7

In [112]:
df3

    A   B    C    D
5  A8  A9  A10  A11
6  B8  B9  B10  B11
7  C8  C9  C10  C11
8  D8  D9  D10  D11

In [113]:
# 열방향 병합
pd.concat([df1, df2, df3])

    A   B    C    D
0  A0  A1   A2   A3
1  B0  B1   B2   B3
2  C0  C1   C2   C3
3  D0  D1   D2   D3
2  A4  A5   A6   A7
3  B4  B5   B6   B7
4  C4  C5   C6   C7
5  D4  D5   D6   D7
5  A8  A9  A10  A11
6  B8  B9  B10  B11
7  C8  C9  C10  C11
8  D8  D9  D10  D11

In [114]:
# 인덱스를 0부터 깔끔하게 재배열
result = pd.concat([df1, df2, df3], ignore_index=True)
result

     A   B    C    D
0   A0  A1   A2   A3
1   B0  B1   B2   B3
2   C0  C1   C2   C3
3   D0  D1   D2   D3
4   A4  A5   A6   A7
5   B4  B5   B6   B7
6   C4  C5   C6   C7
7   D4  D5   D6   D7
8   A8  A9  A10  A11
9   B8  B9  B10  B11
10  C8  C9  C10  C11
11  D8  D9  D10  D11